roles/flask/app/kks/forms.py
from wtforms import Form, SelectField, StringField, DateTimeField, IntegerField, TextField, SubmitField
from wtforms.validators import IPAddress, DataRequired
from flask_wtf import FlaskForm 

class PostForm(FlaskForm):
    mask = SelectField('Маска сети', choices=(("/24", "/24"),("/25", "/25"),("/26", "/26"),("/27", "/27"),("/28", "/28"),("/29", "/29"),("/30", "/30"),("/31", "/31")))
    ip = StringField('сеть', validators = [IPAddress(ipv4=True, ipv6=False,  message = None), DataRequired()])
    vlan = IntegerField('Номер VLAN')
    vlan_name = StringField('Название VLAN')
    filial = SelectField('Организация/филиал', choices=(("АУП", "АУП"), ("АНУ", "АНУ"), ("ТНУ", "ТНУ"), ("КНУ", "КНУ"), ("ЧелНУ", "ЧелНУ"), ("ЧерНУ", "ЧерНУ"), ("СУПЛАВ", "СУПЛАВ")))
    ploshadka = StringField('Площадка (Введите правильно, в соответствии со  списком площадок организации):')
    ploshadka_det = StringField('Уточнения по сети (для чего, где используется)')
    getway = StringField('IP-адрес шлюза (Введите правильно, с учетом маски подсети):', validators = [IPAddress(ipv4=True, ipv6=False,  message = None), DataRequired()])

    primech = TextField('Комментарий')
    name = StringField('DNS имя')

    Submit_1 = SubmitField('Добавить сеть')

#ИС
class IsForm(FlaskForm):
    kr_name = StringField('Краткое наименование ИС', [DataRequired()]) # краткое имя
    name = StringField('Полное наименование ИС', [DataRequired()]) # полное имя
    kategor = SelectField('Категория обробарываемой информации', choices=(("K", "K"), ("KT", "KT"), ("ПНД", "ПНД"))) # категория обробарываемой информации (к/кт/ПНд)
    tip = SelectField('Тип системы', choices=(("локальная", "локальная"), ("корпоративная", "корпоративная"))) # тип системы (локальная/корпоративная)
    Submit_2 = SubmitField('Добавить ИС')






    



    

roles/flask/app/kks/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required
from models import kkss, iss
from .forms import PostForm, IsForm
import ipaddress
from app import db



kks = Blueprint('kks', __name__, template_folder='templates')

@kks.route('/net_create', methods = ['POST', 'GET'])
@login_required
def net_create():
    form2 = IsForm()
    form = PostForm()
    if form.Submit_1.data:
        mask = request.form['mask']
        ip = request.form['ip']
        filial = request.form['filial'] 
        ploshadka = request.form['ploshadka']
        vlan = request.form['vlan']
        vlan_name = request.form['vlan_name']
        ploshadka_det = request.form['ploshadka_det']
        getway = request.form['getway']
        net = ipaddress.ip_network(ip + mask)
        broadcast = net.broadcast_address
        sr = kkss.query.filter(kkss.ploshadka == ploshadka, kkss.filial == filial).first()
        q = 0
        if sr is None:
            flag = '1'
        else:
            flag = '0'
        try:
            for ipp in net:
                if flag == "1" and q == 0:
                    setka = kkss(ip = str(ipp), broadcast = str(broadcast), mask = mask, subnet = str(net), getway = getway, filial = filial, ploshadka = ploshadka, flag = '1', vlan = vlan, vlan_name = vlan_name, ploshadka_det = ploshadka_det)
                    db.session.add(setka)  
                    db.session.commit()
                    q = q + 1
                else:
                    setka = kkss(ip = str(ipp), broadcast = str(broadcast), mask = mask, subnet = str(net), getway = getway, filial = filial, ploshadka = ploshadka, flag = '0', vlan = vlan, vlan_name = vlan_name, ploshadka_det = ploshadka_det)
                    db.session.add(setka)  
                    db.session.commit()
            return redirect(url_for('kks.index'))
        except:
            print('Something wrong s setkami')
    elif form2.Submit_2.data:
        kr_name = request.form['kr_name']
        name = request.form['name']
        kategor = request.form['kategor']
        tip =  request.form['tip']
        try:
            sistema = iss(kr_name = str(kr_name), name = str(name), kategor = str(kategor), tip = str(tip))
            db.session.add(sistema)
            db.session.commit()
            return redirect(url_for('kks.index'))
        except:
            print('Something wrong s ISami')
    else:
        return render_template('kks/net_create.html', form=form, form2 = form2)
    
        

@kks.route('/kks')
@login_required
def index():
    q = request.args.get('q')
    q1 = request.args.get('q1')
    if q:
        searchs = kkss.query.filter(kkss.ip.contains(q) | kkss.name.contains(q)).all()
        return render_template('kks/searchs.html', searchs = searchs)
    if q1:
        sistema = iss.query.filter(iss.kr_name.contains(q1)).all()
        return render_template('kks/perech_is.html', sistema = sistema)
    xs = kkss.query.filter(kkss.filial == "АУП", kkss.flag == "1").all()
    ans = kkss.query.filter(kkss.filial == "АНУ", kkss.flag == "1").all()
    chels = kkss.query.filter(kkss.filial == "ЧелНУ", kkss.flag == "1").all()
    cher = kkss.query.filter(kkss.filial == "ЧерНУ", kkss.flag == "1").all()
    return render_template('kks/index.html', xs = xs, ans = ans, chels = chels, cher = cher)





@kks.route('/<plosh_detail>_<fil>')
@login_required
def ploshadka_detail(plosh_detail, fil):
    infos = kkss.query.filter(kkss.ploshadka == str(plosh_detail), kkss.ip == kkss.broadcast, kkss.filial == str(fil)).all()
    ips = kkss.query.filter(kkss.ploshadka == str(plosh_detail)).all()
    ipy = kkss.query.filter(kkss.ploshadka == str(plosh_detail), kkss.filial == str(fil)) # все ip с площадки например Черну АУП
    return render_template('kks/ploshadka_detail.html', infos = infos, ips = ips)




@kks.route('/<ip_detail> ', methods = ['POST', 'GET'])
@login_required
def ip_detail(ip_detail):
    ipp = kkss.query.filter(kkss.id == ip_detail).first()
    isy = ipp.is_ip
    x1 = kkss.query.filter(kkss.ip == str(ipaddress.ip_address(ipp.ip) + 1)).first()
    x2 = kkss.query.filter(kkss.ip == str(ipaddress.ip_address(ipp.ip) - 1)).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=ipp)
        form.populate_obj(ipp)
        db.session.commit()
        return redirect(url_for('kks.ip_detail', ip_detail = ipp.id))
    else:
        form = PostForm(obj = ipp)
        return render_template('kks/ip_detail.html', ipp = ipp, form = form, x1 = x1, x2 = x2, isy = isy)
    



@kks.route('/perech_is_<is_det>', methods = ['POST', 'GET'])  
@login_required
def is_det(is_det):
    isss = iss.query.filter(iss.id == is_det).first()
    ipy = isss.ip_is.all()
    q2 = request.args.get('q2')
    if q2:
        x = kkss.query.filter(kkss.ip.contains(q2)).first() # добавить alert если ip нет в списке ККС
        x.is_ip.append(isss) # связываем ИП ККС и ИС
        db.session.add(x)  
        db.session.commit()
        return redirect(url_for('kks.is_det', is_det = isss.id)) 
    if request.method == 'POST':
        form = IsForm(formdata=request.form, obj=isss)
        form.populate_obj(isss)
        db.session.commit()
        return redirect(url_for('kks.is_det', is_det = isss.id))
    else:
        form = IsForm(obj = isss)
        return render_template('kks/is_det.html', form = form, isss = isss, ipy = ipy)   



@kks.route('/perech_is')
@login_required
def perech_is():
    sistema = iss.query.all()
    return render_template('kks/perech_is.html', sistema = sistema)



 



    

roles/flask/app/kks/templates/kks/index.html
{%extends 'base.html'%}

{%block title%}
 Корпоративная сеть
{%endblock%}

{%block main%}
<div class = 'container-fluid'>
    <h1 class = "text-center mb-3">Основные компоненты ККС</h1>
    <div class = 'row'>
        <div class = 'col-lg-6'>
            <div class="card col-lg-10 mb-3 border-primary">
                <div class="card-body">
                    <h4 class="card-title">Список площадок</h4>
                    <h6 class = "col-lg-8 text-center">АУП</h6>
                    {% for x in xs%}
                    <div class = "list-group col-lg-10">
                        <a href="{{ url_for('kks.ploshadka_detail', plosh_detail = x.ploshadka, fil = x.filial) }}" class="list-group-item list-group-item-action list-group-item-primary">{{x.ploshadka}}</a>
                    </div>
                    {% endfor %}
                    <h6 class = "col-lg-8 text-center">Арланское НУ</h6>
                    {% for a in ans%}
                    <div class = "list-group col-lg-10">
                        <a href="{{ url_for('kks.ploshadka_detail', plosh_detail = a.ploshadka, fil = a.filial) }}" class="list-group-item list-group-item-action list-group-item-primary">{{a.ploshadka}}</a>
                    </div>
                    {% endfor %}
                    <h6 class = "col-lg-8 text-center">Челябинское НУ</h6>
                    {% for ch in chels%}
                    <div class = "list-group col-lg-10">
                        <a href="{{ url_for('kks.ploshadka_detail', plosh_detail = ch.ploshadka , fil = ch.filial) }}" class="list-group-item list-group-item-action list-group-item-primary">{{ch.ploshadka}}</a>
                    </div>
                    {% endfor %}
                    <h6 class = "col-lg-8 text-center">Черекасское НУ</h6>
                    {% for cer in cher%}
                    <div class = "list-group col-lg-10">
                        <a href="{{ url_for('kks.ploshadka_detail', plosh_detail = cer.ploshadka , fil = cer.filial) }}" class="list-group-item list-group-item-action list-group-item-primary">{{cer.ploshadka}}</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class = 'col-lg-6'>
            <div class="card col-lg-10 mb-3 border-primary">
                <div class="card-body">
                    <h4 class="card-title">Поиск по IP</h4>
                    <form method="GET">
                        <div class = "form-group col-lg-8">
                            <label for = "inputAddress">IP-адрес или HOST name</label>
                            <input type="text" class="form-control" id = "inputAddress" placeholder="10.10.10.10 или WUS01-IVANOVII" name="q" value="{{ request.args.get('q', '') }}">
                        </div>
                        <div class = "btn-toolbar" role = "toolbar" aria-label = "Toolbar with button groups">
                            <div class = "btn-group mr-3" role = "group" aria-label="1 group">
                                <button type ="submit" class="btn btn-primary">Поиск</button>
                            </div>
                            <div class = "btn-group mr-3" role = "group" aria-label="2 group">
                                <a class = "btn btn-primary" href = "{{ url_for('kks.net_create')}}" role = "button"> Добавить сеть / Добавить ИС</a>
                            </div>
                        </div>
                    </form> 
                </div>
                <div class="card-body">
                    <h4 class="card-title">Поиск ИС</h4>
                    <form method="GET">
                        <div class = "form-group col-lg-8">
                            <label for = "inputAddress3">ID номер или Краткое наименование</label>
                            <input type="text" class="form-control" id = "inputAddress3" name="q1" value="{{ request.args.get('q1', '') }}">
                        </div>
                        <div class = "btn-toolbar" role = "toolbar" aria-label = "Toolbar with button groups">
                            <div class = "btn-group mr-3" role = "group" aria-label="3 group">
                                <button type ="submit" class="btn btn-primary">Поиск</button>
                            </div>
                            <!--<div class = "btn-group mr-3" role = "group" aria-label="4 group">
                                <a class = "btn btn-primary" href = "{{ url_for('kks.net_create')}}" role = "button"> Добавить ИС</a>
                            </div> -->
                            <div class = "btn-group mr-3" role = "group" aria-label="5 group">
                                <a class = "btn btn-primary" href = "{{ url_for('kks.perech_is')}}" role = "button"> Перечень ИС</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

roles/flask/app/kks/templates/kks/ip_detail.html
{%extends 'base.html'%}

{%block title%}
 Инфо по IP-адресу
{%endblock%}


{%block main%}
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}" defer></script>
<div class = 'container-fluid'>
    <h1 class = "text-center mb-3"></h1>
    <div class = 'row'>
        <div class = 'col-lg-6'>
            <div class="card col-lg-10 border-primary mb-3">
                <div class="card-body">
                    <h4 class="card-title"> Инвинтаризация IP-адреса </h4>
                    {% for ip_metr in ip_metrik%}
                    <div class = "list-group col-lg-10 mb-3">
                        <li class="list-group-item list-group-item-primary"><h5>IP-адрес --- <span class="badge badge-primary">{{ip_metr.ip}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5> Время сканирования --- <span  class="badge badge-primary">{{ip_metr.host_time}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>FQDN --- <span  class="badge badge-primary">{{ip_metr.fqdn}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>NETBIOS --- <span  class="badge badge-primary">{{ip_metr.netbios}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>ping --- <span  class="badge badge-primary">{{ip_metr.ping}}</span></h5></li>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class = 'col-lg-6'>
            <div class="card col-lg-10 border-primary mb-3">
                <div class="card-body">
                    <h4 class="card-title"> <a type="button" class="btn btn-outline-primary" href="{{ url_for('kks.ip_detail', ip_detail = x2.id) }}">{{x2.ip}}</a> >>> {{ipp.ip}} >>> <a type="button" class="btn btn-outline-primary" href="{{ url_for('kks.ip_detail', ip_detail = x1.id) }}">{{x1.ip}}</a> </h4>
                    <div class = "list-group col-lg-10">
                        <li class="list-group-item list-group-item-primary"><h5>IP-адрес --- <span class="badge badge-primary">{{ipp.ip}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5> DNS имя --- <span  class="badge badge-primary">{{ipp.name}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>VLAN --- <span  class="badge badge-primary"> {{ipp.vlan}} </span> <span  class="badge badge-primary">{{ipp.vlan_name}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5> Информационная система (если есть) --- </h5>
                            {% for iss in isy%}
                                <a type="button" class="btn btn-primary" href="{{ url_for('kks.is_det', is_det = iss.id) }}">{{iss.name}}</a>
                            {% endfor %}
                        </li>
                        <li class="list-group-item list-group-item-primary"><h5>Сеть --- <span  class="badge badge-primary">{{ipp.subnet}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>GetWay --- <span  class="badge badge-primary">{{ipp.getway}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>Broadcast --- <span  class="badge badge-primary">{{ipp.broadcast}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>Филиал --- <span  class="badge badge-primary">{{ipp.filial}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>Площадка --- <span  class="badge badge-primary">{{ipp.ploshadka}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>Расположение на пложадке --- <span  class="badge badge-primary">{{ipp.ploshadka_det}}</span></h5></li>
                        <li class="list-group-item list-group-item-primary"><h5>Комментарий <span  class="badge badge-primary">{{ipp.primech}}</span></h5></li>
                        <div class="accordion" id="accordionExample">
                            <div class="card">
                              <div class="card-header" id="headingOne">
                                <h2 class="mb-0">
                                  <button class="btn btn-success text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Добавить/Изменить
                                  </button>
                                </h2>
                              </div>
                              <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                <div class="card-body">
                                    <form action="{{ url_for('kks.ip_detail', ip_detail = ipp.id) }}", method="POST">
                                        <div class = "form-group col-lg-8">
                                            {{ form.name.label }} {{ form.name(class = "form-control")}}
                                        </div>
                                        <div class = "form-group col-lg-8">
                                            {{ form.primech.label }} {{ form.primech(class = "form-control")}}
                                        </div>
                                        <button type="submit" class="btn btn-success">Добавить</button>
                                      </form>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

roles/flask/app/kks/templates/kks/is_det.html
{%extends 'base.html'%}


{%block title%}
 Инфо по ИС
{%endblock%}

{%block main%}
<!-- bootstrap -->
<link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}" defer></script>
<script src="{{url_for('static', filename='js/popper.min.js')}}" async></script>
<script src="{{url_for('static', filename='js/jquery-3.3.1.slim.min.js')}}" defer></script>
<!-- bootstrap -->
<link rel="stylesheet" href="{{url_for('static', filename='css/Chart.min.css')}}"> 
<script src="{{url_for('static', filename='js/Chart.min.js')}}" async></script>
<link rel="stylesheet" href="{{url_for('static', filename='css/Chart.css')}}"> 
<script src="{{url_for('static', filename='js/Chart.js')}}" defer></script>
<script src="{{url_for('static', filename='js/Chart.bundle.js')}}" defer></script>
<script src="{{url_for('static', filename='js/Chart.bundle.min.js')}}" async></script>
<!-- bootstrap -->
<div class="container-fluid">
    <h2 class = "text-center mb-3">Полная информация по ИС - {{isss.kr_name}}</h2>
    <div class="row justify-content-center">
        <div class="card col-lg-11 mb-3 border-primary">
            <div class="card-body">
                <table class ="table table-bordered table-hover table-sm">
                    <tr><td class="table-primary">Краткое наименование ИС</td> <td>{{isss.kr_name}}</td></tr>
                    <tr><td class="table-primary">Полное наименование ИС</td><td>{{isss.name}}</td></tr>
                    <tr><td class="table-primary">Сервера<br>
                        <form method="GET">
                            <div class = "form-group col-lg-8">
                                <input type="text" class="form-control col-lg-4" id = "inputAddress" placeholder="Введите IP" name="q2" value="{{ request.args.get('q2', '') }}">
                                <button type ="submit" class="btn btn-success">Добавить</button>
                            </div>
                        </form> 
                    </td><td>
                        {% for ip in ipy%}
                        <a href="{{ url_for('kks.ip_detail', ip_detail = ip.id)  }}">{{ip.ip}}</a> <br>
                        {% endfor %}
                    </td></tr>
                    <tr><td class="table-primary">Тип ИС (локальная/корпоративная)</td><td>{{isss.tip}}</td></tr>
                    <tr><td class="table-primary">Категория обробарываемой информации (к/кт/ПНд)</td><td>{{isss.kategor}}</td></tr>
                    <tr><td class="table-primary">Назначение ИС (прикладная/инфраструктурная/СЗИ)</td><td>{{isss.naznach}}</td></tr>
                    <tr><td class="table-primary">Дата ввода ИС в ПЭ</td><td>{{isss.data_vvoda}}</td></tr>
                    <tr><td class="table-primary">Наименование организации (подразделения), отвечающего за ИС</td><td>{{isss.zakazchik}}</td></tr>
                    <tr><td class="table-primary">Дата последнего проведения ИБ ИС</td><td>{{isss.data_ib}}</td></tr>
                    <tr><td class="table-primary">Примечание</td><td>{{isss.primech}}</td></tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="card col-lg-10 mb-3 border-primary">
            <div class="card-body">
                <form action="{{ url_for('kks.is_det', is_det = isss.id) }}", method="POST">
                    <div class = "form-group col-lg-8">
                        {{ form.name.label }} {{ form.name(class = "form-control")}}
                    </div>
                    <div class = "form-group col-lg-8">
                        {{ form.kr_name.label }} {{ form.kr_name(class = "form-control")}}
                    </div>
                    <button type="submit" class="btn btn-success">Внести изменения</button>
                </form>
            </div>
        </div>
    </div> 
</div>
{%endblock%}

roles/flask/app/kks/templates/kks/net_create.html
{%extends 'base.html'%}

{%block title%}
 Добавить сеть
{%endblock%}

{%block main%}
<div class = "container-fluid">
    <h2 class = "text-center mb-3">Добавить компоненты ККС</h2>
    <div class = "row">
      <div class = "col-lg-6 md-3">
          <div class = "card col-lg-9 mb-3 border-primary">
            <div class="card-body">
              <h4 class="card-title">Добавить сеть</h4>
              <form action="{{ url_for('kks.net_create') }}" method="POST" name="form">
                <div class = "form-group col-lg-8">
                  {{ form.mask.label}} {{ form.mask(class="form-control", placeholder="/29")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.ip.label }} {{ form.ip(class = "form-control", placeholder="10.10.10.0", pattern="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.getway.label }} {{ form.getway(class = "form-control", placeholder="10.10.10.1", pattern="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.vlan.label }} {{ form.vlan(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.vlan_name.label }} {{ form.vlan_name(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.filial.label }} {{ form.filial(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.ploshadka.label }} {{ form.ploshadka(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.ploshadka_det.label }} {{ form.ploshadka_det(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form.Submit_1(class="btn btn-primary")}}
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class = "col-lg-6 md-3">
          <div class = "card col-lg-9 mb-3 border-primary">
            <div class="card-body">
              <h4 class="card-title">Добавить ИС</h4>
              <form action="{{ url_for('kks.net_create') }}" method="POST" name="form2">
                <div class = "form-group col-lg-8">
                  {{ form2.kr_name.label }} {{ form2.kr_name(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form2.name.label }} {{ form2.name(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form2.kategor.label }} {{ form2.kategor(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form2.tip.label }} {{ form2.tip(class = "form-control")}}
                </div>
                <div class = "form-group col-lg-8">
                  {{ form2.Submit_2(class="btn btn-primary")}}
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
</div>
{%endblock%}

roles/flask/app/kks/templates/kks/perech_is.html
{%extends 'base.html'%}

{%block title%}
  Перечень ИС
{%endblock%}


{%block main%}
    <div class = "container-fluid">
        <h2 class = "text-center mb-3">Информационные Системы ККС</h2>
        <div class="card-body">
            <table class ="table table-bordered table-hover table-sm">
            <thead>
                <tr class="table-primary">
                    <th>Краткое наименование</th>
                    <th>Полное наименование</th>
                    <th>Категория обрабатываемой информации</th>
                    <th>Тип обрабатываемой информации</th>
                </tr>
            </thead>
            {% for sis in sistema%}
                <tbody>
                    <td><a href="{{ url_for('kks.is_det', is_det = sis.id) }}">{{sis.kr_name}}</a></td> 
                    <td>{{sis.name}}</td>
                    <td>{{sis.kategor}}</td>
                    <td>{{sis.tip}}</td>
                </tbody>
            {% endfor %}
            </table>
        </div>
    </div>

{%endblock%}

roles/flask/app/kks/templates/kks/ploshadka_detail.html
{%extends 'base.html'%}

{%block title%}
 Инфо по площадке
{%endblock%}


{%block main%}
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}" defer></script> 
    <div class = "container-fluid">
        <h2 class = "text-center mb-3">Информация по подсетям площадки</h2>
        <div class="accordion" id="accordionExample">
            {% for i in infos%}
            <div class="card">
              <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                  <button class="btn btn-block btn-lg text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse{{i.id}}" aria-expanded="true" aria-controls="collapse{{i.id}}"  style="background-color: #2585c9; color: azure;">
                    {{i.subnet}}
                  </button> 
                </h2> 
                <table class ="table table-bordered table-sm">
                  <thead>
                    <tr class="table-primary">
                      <th>{{i.ploshadka_det}}</th>
                      <th> VLAN --> {{i.vlan}} - {{i.vlan_name}} </th>
                      <th>GetWay --> {{i.getway}}</th>
                      <th>broadcast --> {{i.broadcast}} </th>
                    </tr>
                  </thead>
                </table>
              </div>
              <div id="collapse{{i.id}}" class="collapse" aria-labelledby="heading{{i.id}}" data-parent="#accordionExample">
                <div class="card-body">
                  <table class ="table table-bordered table-hover table-sm">
                    <thead>
                        <tr class="table-primary">
                            <th>IP-адрес</th>
                            <th>Хост-name</th>
                            <th>Комментарий</th>
                        </tr>
                    </thead>
                    {% for ip in ips%}
                      {% if i.subnet == ip.subnet %}
                        <tbody>
                            <td><a href="{{ url_for('kks.ip_detail', ip_detail = ip.id) }}">{{ip.ip}}</a></td>
                            <td>{{ip.name}}</td>
                            <td>{{ip.primech}}</td>
                        </tbody>
                      {% endif %}
                    {% endfor %}
                  </table>
                </div>
              </div>
            {% endfor %}
            </div>
        </div>
    </div>

{%endblock%}

roles/flask/app/kks/templates/kks/searchs.html
{%extends 'base.html'%}

{%block title%}
 Результат поиска
{%endblock%}


{%block main%}
    <div class = "container-fluid">
        <h2 class = "text-center mb-3">Результат поиска</h2>
        <div class="card-body">
            <table class ="table table-bordered table-hover table-sm">
            <thead>
                <tr class="table-primary">
                    <th>IP-адрес</th>
                    <th>Хост-name</th>
                    <th>Комментарий</th>
                </tr>
            </thead>
            {% for ip in searchs%}
                <tbody>
                    <td><a href="{{ url_for('kks.ip_detail', ip_detail = ip.id) }}">{{ip.ip}}</a></td> 
                    <td>{{ip.name}}</td>
                    <td>{{ip.primech}}</td>
                </tbody>
            {% endfor %}
            </table>
        </div>
    </div>

{%endblock%}